-- T003 / data-model.md — esquema v1 de la feature 0001-alta-pedido
CREATE TABLE pedidos (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_nombre  VARCHAR(120)  NOT NULL,
    cliente_email   VARCHAR(254)  NOT NULL,
    estado          VARCHAR(20)   NOT NULL DEFAULT 'ABIERTO',
    total           NUMERIC(12,2) NOT NULL,
    creado_en       TIMESTAMP     NOT NULL DEFAULT now()
);

CREATE TABLE lineas_pedido (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_id        BIGINT        NOT NULL REFERENCES pedidos(id) ON DELETE CASCADE,
    descripcion      VARCHAR(200)  NOT NULL,
    cantidad         INTEGER       NOT NULL CHECK (cantidad >= 1),
    precio_unitario  NUMERIC(12,2) NOT NULL CHECK (precio_unitario > 0)
);

CREATE INDEX ix_lineas_pedido_pedido_id ON lineas_pedido (pedido_id);
CREATE INDEX ix_pedidos_creado_en ON pedidos (creado_en DESC);
